name: CI

on: [ push ]

jobs:
  test-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          #node-version: 24.7.0 # @see https://github.com/npm/cli/issues/8767
          node-version: 24.11.0
      - name: Install dependencies
        working-directory: ./ui
        run: npm ci
      - name: Build
        working-directory: ./ui
        run: npm run build
      - name: Test
        working-directory: ./ui
        run: npm test
      - name: Lint
        working-directory: ./ui
        run: npm run lint
      - name: Check fmt
        working-directory: ./ui
        run: npm run fmt

  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Fake ui dist
        run: mkdir -p ui/dist/browser && touch ui/dist/browser/empty

      - name: Test
        run: make test

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
