name: CI

on: [ push ]

jobs:
  test-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install dependencies
        working-directory: ./ui
        run: npm ci
      - name: Test
        working-directory: ./ui
        run: npm test
      - name: Lint
        working-directory: ./ui
        run: npm run lint
      - name: Check fmt
        working-directory: ./ui
        run: npx prettier . --check

  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Test
        run: make test

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
